services:
  mysql:
    image: 'mysql:latest'
    container_name: mysql-db
    environment:
      - 'MYSQL_DATABASE=mydatabase'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306:3306'
    volumes:
      - /home/mysql-data:/var/lib/mysql
    networks:
      my-network:

  spring:
    build:
      context: out/artifacts
      dockerfile: Dockerfile
    container_name: reiltor-app
    ports:
      - '8083:8083'
    networks:
      my-network:

networks:
  my-network:

